services:
  - type: web
    name: cleanqueue-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "3000"
      - key: FRONTEND_URL
        sync: false
      - key: REDIRECT_URI
        sync: false
