const fs = require('fs');
const path = require('path');

const DEFAULT_API_URL = 'https://cqwaitlist.onrender.com';
const apiUrl = (
  process.env.PUBLIC_API_URL ||
  process.env.BACKEND_URL ||
  DEFAULT_API_URL
).replace(/\/$/, '');

const content = `// Auto-generated by scripts/generate-config.js — do not edit manually on Netlify builds
window.CLEANQUEUE_CONFIG = {
  API_URL: ${JSON.stringify(apiUrl)}
};
`;

const outPath = path.join(__dirname, '..', 'public', 'config.js');
fs.writeFileSync(outPath, content);
console.log(`[config] geschrieben: ${outPath} (API_URL=${apiUrl || '(same origin)'})`);
