/** Re-exports from ui.ts — legacy import path bleibt kompatibel. */
export {
  COLORS,
  EMOJI,
  primaryEmbed,
  brandEmbed,
  successEmbed,
  errorEmbed,
  warningEmbed,
  infoEmbed,
  modCaseEmbed,
  welcomeEmbed,
  levelUpEmbed,
  profileEmbed,
  rulesEmbed,
  helpEmbed,
  modulesEmbed,
  statusEmbed,
  progressBar,
} from './ui';
